### ISSUE TITLE
I2C

### ISSUE THREAD

**Issue by Robo-NK47** [i2cy/CH347-HIDAPI#1]
Hi guys,

Is there support in I2C communication??

**Comment by i2cy** [comment]
Since I do not need i2c communication currently, no. But I may add the support for I2c later since it uses usb hid communication and it should be easy.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Nadav K. ***@***.***>
Sent: Saturday, May 6, 2023 7:05:06 AM
To: i2cy/CH347-HIDAPI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [i2cy/CH347-HIDAPI] I2C (Issue #1)


Hi guys,

Is there support in I2C communication??

―

**Comment by Robo-NK47** [comment]
Thank you for your response :-)

I really need this communication type and don't have the technical abilities to write it at this time.
Do you have any tips? Are you capable of doing it?

**Comment by i2cy** [comment]
Sorry I am not available for this update recently, things have been busy lately. I will update the I2C support once I got the spare time.
发件人: Nadav ***@***.***>
发送时间: 2023年5月6日 15:00
收件人: ***@***.***>
抄送: Icy ***@***.***>; ***@***.***>
主题: Re: [i2cy/CH347-HIDAPI] I2C (Issue #1)


Thank you for your response :-)

I really need this communication type and don't have the technical abilities to write it at this time.
Do you have any tips? Are you capable of doing it?

―

**Comment by i2cy** [comment]
an update of this repositories should probably be committed next mons.
